# Generated by Django 5.2.4 on 2025-08-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elite_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
