# Generated by Django 5.2.6 on 2025-10-11 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elite_app', '0003_user_is_active_staff_user_position_user_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EliteHands', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(default='157 Gorge Rd E #402, Victoria, BC V9A 6Y2, Canada', max_length=255)),
                ('map_embed_url', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('driver', 'Driver'), ('mover', 'Mover'), ('cleaner', 'Cleaner'), ('packing_specialist', 'Packing Specialist'), ('event_planner', 'Event Planner'), ('event_assistant', 'Event Assistant'), ('logistics', 'Logistics'), ('customer_service', 'Customer Service'), ('manager', 'Manager')], max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='elite_app.booking')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_assignments',
                'unique_together': {('booking', 'staff')},
            },
        ),
    ]
